### ISSUE TITLE
make all plots square (except maybe time series)

### ISSUE THREAD

**Issue by cdormann** [biometry/APES#15]
I think that all plots should be square (except maybe time-series plots).
Apparently the .Rmd default is fig.width=7 and fig.height=5. This can be changed in the settings at the top of the .Rmd file.

My .Rmd header looks like this:
---
title: "Diversity indices, functional and phylogenetic diversity"
author: "Carsten Dormann"
date: "15 Januar 2015"
output: 
   html_document:
      fig_width: 5
---
```{r, echo=FALSE}
library(knitr)
opts_knit$set(global.par=TRUE) # keep par() from one chunck to the next!
opts_chunk$set(cache=TRUE,fig.align='center') # keep objects once they were produced
```

**Comment by AndreaJO** [comment]
done
