### ISSUE TITLE
Missing description

### ISSUE THREAD

**Issue by ngwalton** [biometry/APES#37]
Hello, I'm unable to install APES with `install_github`. When I run `devtools::install_github("biometry/APES")` I get the following message: 

```
Downloading GitHub repo biometry/APES@master
from URL https://api.github.com/repos/biometry/APES/zipball/master
Installation failed: NULL : Does not appear to be an R package (no DESCRIPTION)
```

I think the package is just missing the DESCRIPTION file.

**Comment by florianhartig** [comment]
apes is not an R package, so you can't install it.
